name: CI

# On every pull request, but only on push to master
on:
  push:
    branches:
    - master
    tags:
    - '*'
  pull_request:
env:
  LATEST_PY_VERSION: '3.9'

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.LATEST_PY_VERSION }}

      - name: install lib postgres
        run: |
          sudo apt update
          wget -q https://www.postgresql.org/media/keys/ACCC4CF8.asc -O- | sudo apt-key add -
          echo "deb [arch=amd64] http://apt.postgresql.org/pub/repos/apt/ focal-pgdg main" | sudo tee /etc/apt/sources.list.d/postgresql.list
          sudo apt update
          sudo apt-get install --yes libpq-dev postgis postgresql-14-postgis-3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirement.txt

      - name: Run Tests
        run: python -m pytest

      # - name: Run Benchmark
      #   run: python -m pytest --benchmark-only --benchmark-columns 'min, max, mean, median' --benchmark-json output.json

      # - name: Store and benchmark result
      #   uses: benchmark-action/github-action-benchmark@v1
      #   with:
      #     name: TiFeatures Benchmarks
      #     tool: 'pytest'
      #     output-file-path: output.json
      #     alert-threshold: '130%'
      #     comment-on-alert: true
      #     fail-on-alert: true
      #     # GitHub API token to make a commit comment
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     # Make a commit on `gh-pages` only if master
      #     auto-push: ${{ github.ref == 'refs/heads/master' }}
      #     benchmark-data-dir-path: benchmarks
